# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieE

  target 'MovieETests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieEUITests' do
    # Pods for testing
  end

  pod 'Alamofire', '~> 4.9.1'
  pod 'SnapKit', '~> 5.0.1'
  pod 'Kingfisher', '~> 6.0'

end
